// Input all of the ordinances here
	var ord2008009 = '<div id="ord2008009"><div class="uk-panel-title">Cainta Municipal Ordinance # 2008-009</div><strong>An Ordinance Amending Article A. "Anti-Jaywalking" of the <i>Traffic Code of Cainta, Rizal (2001)</i></strong><p><i>Enacted July 28, 2008</i></p><details><summary>More Info</summary><p>Walking across a street outside of the pedestrian lane, crossing the street in disregard of traffic rules and regulations (including hand and electronic trafic signals), and walking beyond or outside the designated street sidewalks which hinders traffic to the motorist or other pedestrians is considered as Jaywalking.</p></p><p><b>Penalties</b>: (1st Offense) Php300.00; (2nd Offense) Php500.00; (3rd Offense) Php1,000.00. [Section 4, as amended.]</p><p><b>Implementing Agencies</b>: <mark>Traffic Management Division of the PNP</mark> and the office of the <mark>Municipal Protection and Safety Office (MPSO)</mark> in cooperation with the  Bantay-Bayan, the Barangay Tanods [As per Section 3.]</p></details></div>';

	var ord2008011 = '<div id="2008011"><div class="uk-panel-title">Cainta Municipal Ordinance # 2008-011</div><strong>An ordinance prohibiting stores to sell and to serve tobacco cigarettes ang liquor to minors and students, and providing penalties for violation</strong><p><i>Enacted July 28, 2008</i></p><p><details><summary>More Info</summary><q>It shall be unlawful for vendors and stores within the jurisdiction of this municipality to sell/serve tobacco cigarettes and liquor to minors.</q></p><p><b>Penalties</b>: (1st Offense) Fine of Php1,000.00; (2nd Offense) Fine of Php2,000.00; (3rd Offense) Revocation of permit or imprisonment of not more than six months and fine of Php2,500.00, or discretion of the competent Court.</p></details></div>';
	
	var ord2008015 = '<div id="2008015"><div class="uk-panel-title">Cainta Municipal Ordinance # 2008-015</div><strong>Ordinance Prohibiting the Passage and/or Entry of all Garbage Trucks in the Municipality of Cainta, Rizal, except Those Providing Services to the Municipality, and Prescribing Penalties for Violation Thereof</strong><p><i>Enacted September 1, 2008</i></p><details><summary>More Info</summary><p>[All kinds of garbage trucks that are not providing services to the Municipality of Cainta shall not pass through all streets of the Municipality.]</p><p><b>Penalties</b> [As per "Penalties, Section 1"]: <ul><li><b><i>For the Driver or Person-in-Charge</i></b> - (1st Offense) A fine of Php1,000.00 or two months jail time or both at the discretion of the court; (2nd Offense) A fine of Php2,000.00 or not more than four months but less than two months jail time or both at the discretion of the court; (3rd Offense) Fine of Php2,500.00 or not more than six months but not less than four months jail time or both at the discretion of the court. A subsidiary imprisonment of Php100.00 per day in case of insolvency are included in each penalty violation.</li><li><b><i>Impounding</i></b> - <q>The garbage or solid/residual wastes hauled in an impounded truck which is not released within a period of two days shall be unloaded and re-loaded to any garbage truck accredited by the Municipality, with or without presence of the driver or registered owner or authorized representative thereof, for proper disposal to a sanitary landfill to avoid decomposition and emission of bad odor in the impounding area and such garbage truck shall not be released unless a transport and tipping fee of P10,000.00 is paid to the Municipality.</q></li></ul></p><p><b>Implementing Agencies</b>: <mark>Cainta PNP</mark>, <mark>Barangay Tanods</mark>, <mark>Office of the Mayor</mark>.</p></details></div>';
	
	var ord2008024 = '<div id="2008024"><div class="uk-panel-title">Cainta Municipal Ordinance # 2008-024</div><strong>An Ordinance Penalizing Prank Callers / Texters within the Municipality of Cainta, Rizal.</strong><p><details><summary>More Info</summary><blockquote><b>Section 1</b> PRANK - A ridiculous or mildly mischievous act and/or to play tricks maliciously to sow panic, fear and/or physical harm to the call / text message recipient.</blockquote><blockquote><b>Section 3</b>. SCOPE AND COVERAGE - Calls / text message made / send through the telephone and mobile phone in residential, commercial and industrial establishments.</blockquote></p><p><b>Penalty</b>: Php2,500.00  but not more than Php5,000.00 or imprisonment of not less than thirty (30) days but not more than (90) days, or both shall be imposed against the offender or upon the discretion of the court. [As per Section 4]</p><p><b>Implementing Agencies</b>: The <mark>Cainta PNP</mark>, <mark>Barangay Officials & Tanods</mark>, <mark>MPSO (Municipal Protection and Safety Office)</mark> [As per Section 6.]</details></p></div>';
	
	var ord2008021 = '<div id="2008021"><div class="uk-panel-title">Cainta Municipal Ordinance # 2008-021</div><strong>An ordinance mandating all Banking, Financial Institutions and Big Scale Business Establishments Operating within The Municipality of Cainta to Install Close Circuit Television(CCTV)</strong><p><i>Enacted October 20, 2008</i></p><p><details><summary>More Info</summary><blockquote><b>Section 1</b>: All banks, pawnshops, other financial institutions and big establishments with an investment of at least two million pesos (Php2,000,000.00) in Cainta, Rizal are hereby mandated to install close circuit television inside and outside their respective premises within ninety (90) days from approval of this ordinance.</blockquote><blockquote><b>Section 3</b>: Preservation of Camera Recording - The banks, pawnshops, other financial institutions and big establishments shall preserve the camera recordings for at least a period of 1 year from the date of its recording.</blockquote></p><p><b>Penalty</b>: Php1,000.00  for violation of Section 1; Php5,000.00 for violation of Section 3. [As per Section 6] The <mark>Municipal Mayor</mark> may withhold the issuance of the Mayorâ€™s Permit to operate its business in Cainta, Rizal for any violation of this Ordinance.</p><p><b>Implementing Agencies</b>: The <mark>Cainta PNP</mark>, <mark>Barangay Officials & Tanods</mark>, <mark>MPSO (Municipal Protection and Safety Office)</mark> [As per Section 6.]</details></p></div>';
	
	var ord2009012 = '<div id="2009012"><div class="uk-panel-title">Cainta Municipal Ordinance # 2009-012</div><strong>An Ordinance Rescinding Article D - "Towing of Stalled or Illegally Parked Motor Vehicles of the <i>Traffic Code of Cainta, Rizal (2001)</i> Under Resolution no. 01-0047 and Municipal Ordinance no. 01-0016</strong><p><i>Enacted November 22, 2010</i></p><p><details><summary>More Info</summary><q><b>WHEREAS</b>, the Sanggunian Bayan deems necessary to rescind Article D. Of subject Traffic Code 2001 due to the reported irregularities in its implementation and to give way for amendments and the preparation of a corresponding guideline, particularly to towing operations.</q></p><p><q>NOW THEREFORE, BE IT ORDAINED AS IT IS HEREBY ORDAINS by by the Sangguniang Bayan of Cainta, Rizal that: <b>Section 1</b>,  Article D (Towing of stalled or illegally parked motor vehicles of the <i>Traffic Code of Cainta, Rizal (2001))</i> is hereby rescinded.</q></details></p></div>';
	
	var ord2010009 = '<div id="2010009"><div class="uk-panel-title">Cainta Municipal Ordinance # 2010-009</div><strong>"Tapat Ko, Linis Ko" Ordinance</strong><p><i>Enacted August 20, 2009</i></p><p><details><summary>More Info</summary><blockquote><b>Section 1</b>. It shall be the responsibility of the owner and/or dweller, lessee, occupant of a residential or commercial establishment to maintain the cleanliness of the sidewalk and streets fronting their residence or establishment.</blockquote></p><p><b>Penalties</b>: (1st Offense) Warning; (2nd and Subsequent Offense) Fine of Php2,000.00. [As per Section 3.]</p><p><b>Implementing Agencies</b>: <mark>Cainta Waste Management Office (WMO)</mark> [As of Section 4.]</details></p></div>';
	
	var ord2011007 = '<div id="2011007"><div class="uk-panel-title">Cainta Municipal Ordinance # 2011-007</div><strong>Express Lane Ordinance for Senior Citizens and Persons with Disabilities</strong><p><details><summary>More Info</summary><q>All public and private establishments in this municipality such as, but not limited to utility companies (water, telephone, and electric), banks and financial institutions, shopping malls, supermarkets, department stores, drugstores, fastfood chain outlets, bus terminals, and governments offices required to provide express lanes for seniors, persons with disabilities.</q> [Section 1]</p><p><q>[...] available only to all senior citizens and persons with disability who are Filipino citizens upon submission of any valid ID as proof of his/her entitlement thereto.</q> [Section 2]</p><p><b>Penalty</b>: A fine of not less than Php1,000.00 but not exceeding Php2,000.00 and imprisonment of not less than six months but not more than two years. [As per Section 3.]</details></p></div>';
	
	var ord2012001 = '<div id="2012001"><div class="uk-panel-title">Cainta Municipal Ordinance # 2012-001</div><strong>An Ordinance Mandating the Establishment of the Cainta Municipal Disaster Risk Reduction and Management Office (CMDRRMO), Defining its Functions Pursuant to Republic Act no. 10121, and for Other Purposes</strong><p><i>Enacted February 6, 2012</i></p><p><details><summary>More Info</summary>[Indicated in this ordinance is the duties and responsibilities of the Municipal DRRMO, which is under the supervision of the office of the <mark>municipal mayor</mark>.]</details></p></div>';
	
	var ord2012003 = '<div id="2012003"><div class="uk-panel-title">Cainta Municipal Ordinance # 2012-003</div><strong>Municipal PDAO Ordinance</strong><p>An ordinance <em>organizing and establishing a Persons with Disability Affairs Office in the Municipality of Cainta</em> providing appropriations for the implementation thereof</p><p><details><summary>More Info</summary>[Indicated in this ordinance is the duties and responsibilities of a PWD Affairs Officer.]</details></p></div>';
		
// Write the ordinances into the 'Latest Ordinances' sidebar (Only three should be displayed, else a longcat scrollbar will appear. At least make it short.)
	

	document.write(ord2008009 + '<hr/>');
	document.write(ord2008011 + '<hr/>');
	document.write(ord2008015 + '<hr/>');
	document.write(ord2008024 + '<hr/>');
	document.write(ord2008021 + '<hr/>');
	document.write(ord2009012 + '<hr/>');
	document.write(ord2010009 + '<hr/>');
	document.write(ord2011007 + '<hr/>');
	document.write(ord2012001 + '<hr/>');
	document.write(ord2012003);
